name: main
on: [push, pull_request]
jobs:
  check_patch_series:
    name: do-we-need-to-run.py
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: do-we-need-to-run.py
      run: python3 do-we-need-to-run.py
  python:
     strategy:
       fail-fast: false
       matrix:
         version: ['3.11', '3.10', '3.9', '3.8']
     uses: ClangBuiltLinux/actions-workflows/.github/workflows/python_lint.yml@main
     with:
       python_version: ${{ matrix.version }}
