name: main
on: [push, pull_request]
jobs:
  check_patch_series:
    name: should_run.py
    runs-on: ubuntu-latest
    container: tuxmake/x86_64_clang-nightly
    steps:
    - uses: actions/checkout@v3
    - name: should_run.py
      run: |
        python3 should_run.py
        case “$?” in
          0) echo should_run=true >>$GITHUB_ENV ;;
          1) exit 1 ;;
          2) echo should_run=false >>$GITHUB_ENV ;;
        esac
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: run
      if: ${{ env.should_run == 'true' }}
      run: echo running...
  python:
     strategy:
       fail-fast: false
       matrix:
         version: ['3.11', '3.10', '3.9', '3.8']
     uses: ClangBuiltLinux/actions-workflows/.github/workflows/python_lint.yml@main
     with:
       python_version: ${{ matrix.version }}
